### ISSUE TITLE
Enable socialveobot access

### ISSUE THREAD

**Issue by mervick** [socialveo/socialveo-docs#1]
Socialveobot has not an access to socialveo-docs

> remote: Permission to socialveo/socialveo-docs.git denied to socialveobot.
fatal: unable to access 'https://*********:*********@github.com/socialveo/socialveo-docs/': The requested URL returned error: 403

@macagoraga , please grant access to socialveobot

**Comment by andreakru** [comment]
Done, read only access

**Comment by mervick** [comment]
Need also write access for auto updating docs

**Comment by andreakru** [comment]
Ok, done, added write access
